baseURL = "https://example.com/"
copyright = "© 2021 Daniel F. Dickinson"
paginate = 3
defaultContentLanguage = "en"
enableGitInfo = false
enableRobotsTXT = false
summaryLength = 25

[params]
  debugTableEnvironment = ["development","production"]
  mainSections = ["post","docs"]
  # Footnotes and TableOfContents don't work properly with a base href set in <head>
  useBaseURL = false
  testStylesInclude = true

# See https://gohugo.io/content-management/multilingual/
# and https://www.regisphilibert.com/blog/2018/08/hugo-multilingual-part-1-managing-content-translation/
[languages]
  [languages.en]
    languageName = ":en:"
    languageAltTitle = "English"
    title = "Mounted Content Subdir Minimal Reproducible Test Case"
    description = "A (sort-of) minimal reproducible test case for regression on 0.89.0+ when using mounts onto subdirectories of ``content``."
    weight = 1
    
[author]
  name = "Daniel F. Dickinson"
  homepage = "https://www.danielfdickinson.ca/"

  [[ author.authors ]]
    name = "Daniel F. Dickinson"
    homepage = "https://www.danielfdickinson.ca/"

[taxonomies]
  category = "categories"
  tag = "tags"

[frontmatter]
  lastmod = ["lastmod",":git",":fileModTime","date","publishDate"]
  date = ["date","publishDate","lastmod",":git",":fileModTime"]
  publishDate = ["publishDate","date","lastmod",":git",":fileModTime"]

[markup]
  [markup.highlight]
    guessSyntax = true
    noClasses = false

[privacy]

  [privacy.vimeo]
    disabled = true

  [privacy.twitter]
    disabled = true

  [privacy.instagram]
    disabled = true

  [privacy.youtube]
    disabled = true

[module]

  [[module.imports]]
    ignoreConfig = true
    ignoreMounts = true
    path = "github.com/danielfdickinson/hugo-debug-tables"

    [[module.imports.mounts]]
      source = "static"
      target = "static"

    [[module.imports.mounts]]
      source = "layouts"
      target = "layouts"

    [[module.imports.mounts]]
      source = "data"
      target = "data"

    [[module.imports.mounts]]
      source = "assets"
      target = "assets"

    [[module.imports.mounts]]
      source = "README.md"
      target = "assets/README-debug-tables.md"

    [[module.imports.mounts]]
      source = "i18n"
      target = "i18n"

    [[module.imports.mounts]]
      source = "archetypes"
      target = "archetypes"

  [[module.imports]]
    path = "github.com/danielfdickinson/hugo-minimal-test"

    [[module.imports.mounts]]
      source = "static"
      target = "static"

    [[module.imports.mounts]]
      source = "layouts"
      target = "layouts"

    [[module.imports.mounts]]
      source = "data"
      target = "data"

    [[module.imports.mounts]]
      source = "assets"
      target = "assets"

    [[module.imports.mounts]]
      source = "README.md"
      target = "assets/README-minimal-test.md"

    [[module.imports.mounts]]
      source = "i18n"
      target = "i18n"

    [[module.imports.mounts]]
      source = "archetypes"
      target = "archetypes"
